[workspace]
resolver = "2"

members = [
    "contracts",
    "factory",
]

[workspace.package]
rust-version = "1.91.1"

[profile.release-with-logs]
inherits = "release"
debug-assertions = true

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[workspace.dependencies.soroban-sdk]
version = "=27.0.3"

[workspace.dependencies.soroban-token-sdk]
version = "=27.0.3"

[workspace.dependencies.sep-41-token]
version = "=2.0.0"
git = "https://github.com/levinson/sep-41-token.git"
rev = "2b9eb2fac1354034b50aa9e6e72c51f85db5d168"

[workspace.dependencies.soroban-fixed-point-math]
version = "=1.6.0"
git = "https://github.com/levinson/soroban-fixed-point-math.git"
rev = "417905c4e9c7ddea114455e98bd9e4abe6f9f5e7"
