-- This file is generated by verification/generate_constants.rs.
-- Do not edit it directly.

import Mathlib

namespace CometPool

def BONE : ℕ := 1000000000000000000
def STROOP : ℕ := 10000000
def INIT_POOL_SUPPLY : ℕ := 1000000000
def MIN_BALANCE : ℕ := 100
def MIN_WEIGHT : ℕ := 1000000
def MAX_WEIGHT : ℕ := 9000000
def MAX_IN_RATIO : ℕ := 3333334
def MAX_OUT_RATIO : ℕ := 3333334
def MIN_FEE : ℕ := 10
def MAX_FEE : ℕ := 1000000
def CPOW_PRECISION : ℕ := 100000000
def MAX_CPOW_ITERS : ℕ := 50
def MAX_CPOW_EXP : ℕ := 10000000000000000000

end CometPool
