#!/usr/bin/env python3
"""Generate deterministic high-precision reference vectors for Comet c_pow tests."""

from __future__ import annotations

import argparse
from decimal import Decimal, ROUND_CEILING, ROUND_FLOOR, localcontext
from itertools import product
from pathlib import Path


SCALE = 10**18
REFERENCE_PRECISION = 160
VERIFY_PRECISION = 240
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "contracts/src/tests/generated_c_pow_vectors.rs"


def fixed(value: str) -> int:
    scaled = Decimal(value) * SCALE
    integral = scaled.to_integral_value()
    if scaled != integral:
        raise ValueError(f"value is not representable with 18 decimals: {value}")
    return int(integral)


def linear_grid(start: int, end: int, count: int) -> list[int]:
    return [start + (end - start) * index // (count - 1) for index in range(count)]


def inputs() -> tuple[list[int], list[int]]:
    # This is a conservative superset of the accepted domains of all six c_pow call paths:
    # swaps, exact-token single-sided operations, and exact-LP single-sided operations.
    bases = set(linear_grid(fixed("0.63"), fixed("1.5000002"), 31))
    bases.update(
        fixed(value)
        for value in (
            "0.63",
            "0.6333333",
            "0.7",
            "0.749999999999999999",
            "0.75",
            "0.750000000000000001",
            "0.8",
            "0.9",
            "0.99",
            "0.99999958",
            "0.999999999999999999",
            "1",
            "1.000000000000000001",
            "1.00000042",
            "1.01",
            "1.1",
            "1.25",
            "1.3",
            "1.3333333",
            "1.333333333333333333",
            "1.499999999999999999",
            "1.5",
            "1.5000002",
        )
    )
    exponents = {
        fixed(value)
        for value in (
            "0.1",
            "0.1000001",
            "0.1111111",
            "0.125",
            "0.1428571",
            "0.2",
            "0.25",
            "0.3333333",
            "0.5",
            "0.6666667",
            "0.8",
            "0.9",
            "0.9999999",
            "1",
            "1.0000001",
            "1.1111111",
            "1.25",
            "1.4285714",
            "1.6666667",
            "1.9999999",
            "2",
            "2.0000001",
            "2.5",
            "3.3333333",
            "5",
            "8.9999999",
            "9",
            "9.0000001",
            "9.9999999",
            "10",
        )
    }
    return sorted(bases), sorted(exponents)


def reference(base_raw: int, exponent_raw: int, precision: int) -> tuple[int, int]:
    with localcontext() as context:
        context.prec = precision
        base = Decimal(base_raw) / Decimal(SCALE)
        exponent = Decimal(exponent_raw) / Decimal(SCALE)
        scaled_result = context.power(base, exponent) * Decimal(SCALE)
        floor = int(scaled_result.to_integral_value(rounding=ROUND_FLOOR))
        ceil = int(scaled_result.to_integral_value(rounding=ROUND_CEILING))
        return floor, ceil


def generate() -> str:
    bases, exponents = inputs()
    vectors: list[tuple[int, int, int, int]] = []
    for base, exponent in product(bases, exponents):
        expected = reference(base, exponent, REFERENCE_PRECISION)
        verified = reference(base, exponent, VERIFY_PRECISION)
        if expected != verified:
            raise RuntimeError(
                f"reference did not stabilize: base={base} exponent={exponent} "
                f"at {REFERENCE_PRECISION} digits={expected}, at {VERIFY_PRECISION} digits={verified}"
            )
        vectors.append((base, exponent, *expected))

    coverage = (
        f"// {len(vectors)} cases cover bases {bases[0]}..{bases[-1]} "
        f"and exponents {exponents[0]}..{exponents[-1]}."
    )
    lines = [
        "// @generated by scripts/generate_c_pow_vectors.py; do not edit.",
        "// References use Decimal power at 160 digits and are verified again at 240 digits.",
        coverage,
        "",
        "#[rustfmt::skip]",
        "pub(crate) const C_POW_HIGH_PRECISION_CASES: &[(i128, i128, i128, i128)] = &[",
    ]
    lines.extend(
        f"    ({base}, {exponent}, {floor}, {ceil}),"
        for base, exponent, floor, ceil in vectors
    )
    lines.extend(["];", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if the generated fixture is stale"
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    generated = generate()

    if args.check:
        if not args.output.exists() or args.output.read_text() != generated:
            raise SystemExit(f"generated fixture is stale: {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
