use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, PartialEq)]
#[repr(u32)]
pub enum Error {
    ErrFinalized = 1,
    ErrNegative = 2,
    ErrMinFee = 3,
    ErrMaxFee = 4,
    ErrNotController = 5,
    ErrInvalidVectorLen = 6,
    AlreadyInitialized = 7,
    ErrIsBound = 8,
    ErrNotBound = 9,
    ErrMaxTokens = 10,
    ErrMinWeight = 11,
    ErrMaxWeight = 12,
    ErrMinBalance = 13,
    ErrFreezeOnlyWithdrawals = 14,
    ErrMinTokens = 15,
    ErrSwapFee = 16,
    ErrMathApprox = 17,
    ErrLimitIn = 18,
    ErrLimitOut = 19,
    ErrMaxOutRatio = 20,
    ErrBadLimitPrice = 21,
    ErrLimitPrice = 22,
    ErrTotalWeight = 23,
    ErrTokenAmountIsNegative = 24,
    ErrNotAuthorizedByAdmin = 25,
    ErrInsufficientAllowance = 26,
    ErrDeauthorized = 27,
    ErrInsufficientBalance = 28,
    ErrAddOverflow = 29,
    ErrSubUnderflow = 30,
    ErrDivInternal = 31,
    ErrMulOverflow = 32,
    ErrCPowBaseTooLow = 33,
    ErrCPowBaseTooHigh = 34,
    ErrInvalidExpirationLedger = 35,
    ErrNegativeOrZero = 36,
    ErrTokenInvalid = 37,
}
